### ISSUE TITLE
Single Cell - Transcript ID Map

### ISSUE THREAD

**Issue by Kanomble** [cejuliano/brown_hydra_genomes#2]
Hi, the provided pipeline example includes a mapping against the first chromosome. 
I would like to create a mapping similar to the mappings in the single cell browser https://research.nhgri.nih.gov/HydraAEP/SingleCellBrowser/. 

Unfortunately I can't find a table that contains a mapping between transcript/gene IDs and the cell types, is there a way to generate such a table? 

I tried to use the raw dropseq library data within the directory [05_hydraAtlasReMap](https://github.com/cejuliano/brown_hydra_genomes/tree/main/05_hydraAtlasReMap), but as outlined above, this is "just" for the first chromosome. How can I access the whole dataset, to rebuild the singlecellbrowser?

**Comment by Kanomble** [comment]
Maybe its just a naming issue: the ids in the dropseq txt files seem to be just for chromosome 1: HVAEP1_XXXXX maybe there is the issue. For example, I can see the ID HVAEP1_G028915 in D03-KI_S1.dge.txt but the correct ID should be HVAEP15_G028915 right?

**Comment by jcazet** [comment]
Hi @Kanomble, I suspect the issue you are having does indeed stem from a naming issue. Unfortunately, during the process of setting up the genome portal the gene IDs were changed somewhat. I've added a README to the [ID_Conversion](https://github.com/cejuliano/brown_hydra_genomes/tree/main/ID_Conversion) subdirectory that should hopefully provide a decent explanation of the changes that were made. I also added a [conversion table](https://github.com/cejuliano/brown_hydra_genomes/blob/main/ID_Conversion/HVAEP.master.conversion.table.csv) to that folder that should hopefully help you convert between the different IDs without too much additional hassle.

I hope that clears things up, but please let me know if things are still unclear.

**Comment by Kanomble** [comment]
This definitely clears things up, thank you!
